const DATA: Record<string, any> = {
    cs: {
        'side.banner.title': 'Konfigurace formuláře',
        'side.banner.button': 'Konfigurovat',
        back: 'Zpět',
        save: 'Uložit',
        'success.message': 'Formulář byl úspěšně uložen',
        'error.message': 'Formulář se nepodařilo uložit',
        'field.add': 'Přidat pole',
        'field.item.textinput': 'Textové pole',
        'field.item.email': 'E-mail',
        'field.item.phone': 'Mobilní číslo',
        'field.item.textarea': 'Víceřádkové pole',
        'field.item.checkbox': 'Zaškrtávací políčko',
        'field.item.file': 'Soubor',
        'field.item.select': 'Výběr možnosti',
        'field.item.submit': 'Tlačítko odeslat',
        'field.item.title': 'Nadpis',
        'field.item.message': 'Textová zpráva',
        'field.item.divider': 'Dělicí čára',
        'field.item.special': 'Speciální pole',
        'field.item.checkboxGroup': 'Skupina zaškrtávacích políček',
        'field.item.productsSelection': 'Výběr produktů',
        'field.item.amount': 'Součet ceny',
        'unsaved.changes.title': 'Neuložené změny',
        'unsaved.changes.message': 'Pokud opustíte tuto stránku, ztratíte neuložené změny.',
        'unsaved.changes.discard': 'Zpět do editoru',
        'unsaved.changes.confirm': 'Odejít bez uložení',
        'attributes.name': 'Klíč pole',
        'attributes.name.hint': 'Klíč je automaticky generován z názvu pole, ale můžete ho změnit',
        'attributes.label': 'Název pole',
        'attributes.placeholder': 'Zástupný text',
        'attributes.required': 'Povinné pole',
        'attributes.maxFileCount': 'Maximální počet souborů',
        'attributes.allowedFileTypes': 'Povolené typy souborů',
        'attributes.maxFileSize': 'Maximální velikost souboru (v MB)',
        'attributes.options': 'Možnosti výběru',
        'attributes.conditions': 'Podmínky zobrazení',
        'attributes.useOnly': 'Pole se neukládá',
        'attributes.codename': 'Kódové označení',
        'attributes.isLarge': 'Velký nadpis',
        'attributes.onFullWidth': 'Na celou šířku',
        'attributes.products': 'Produkty',
        'attributes.fields': 'Pole zahrnutá do výpočtu',
        'attributes.conditionsEval': 'Vyhodnocení podmínek',
        'select.placeholder': 'Vyberte možnost',
        'select.field': 'Vyberte pole',
        'select.operator': 'Operátor',
        'operator.equals': 'je rovno',
        'operator.not-equals': 'není rovno',
        'operator.contains': 'obsahuje',
        'operator.not-contains': 'neobsahuje',
        'operator.empty': 'je prázdné',
        'operator.not-empty': 'není prázdné',
        'operator.has-checked': 'má zaškrtnuto',
        images: 'Obrázky',
        audios: 'Zvuky',
        videos: 'Videa',
        files: 'Soubory',
        add: 'Přidat',
        'option.title': 'Název možnosti',
        checked: 'Zaškrtnuto',
        unchecked: 'Není zaškrtnuto',
        'deleted.field': 'Smazané pole',
        'no.fields': 'Formulář neobsahuje žádná pole',
        yes: 'Ano',
        no: 'Ne',
        'product.name': 'Název produktu',
        'product.price': 'Cena produktu',
        and: 'Všechny',
        or: 'Alespoň jedna',
        'button.text': 'Text tlačítka',
    },
    en: {
        'side.banner.title': 'Form Configuration',
        'side.banner.button': 'Configure',
        back: 'Back',
        save: 'Save',
        'success.message': 'The form was successfully saved',
        'error.message': 'Failed to save the form',
        'field.add': 'Add field',
        'field.item.textinput': 'Text field',
        'field.item.email': 'Email',
        'field.item.phone': 'Mobile number',
        'field.item.textarea': 'Multiline field',
        'field.item.checkbox': 'Checkbox',
        'field.item.file': 'File',
        'field.item.select': 'Select option',
        'field.item.submit': 'Submit button',
        'field.item.title': 'Title',
        'field.item.message': 'Text message',
        'field.item.divider': 'Divider',
        'field.item.special': 'Special field',
        'field.item.checkboxGroup': 'Checkbox group',
        'field.item.productsSelection': 'Product selection',
        'field.item.amount': 'Total price',
        'unsaved.changes.title': 'Unsaved changes',
        'unsaved.changes.message': 'If you leave this page, you will lose unsaved changes.',
        'unsaved.changes.discard': 'Back to editor',
        'unsaved.changes.confirm': 'Leave without saving',
        'attributes.name': 'Field key',
        'attributes.name.hint': 'The key is automatically generated from the field name, but you can change it',
        'attributes.label': 'Field name',
        'attributes.placeholder': 'Placeholder text',
        'attributes.required': 'Required field',
        'attributes.maxFileCount': 'Maximum number of files',
        'attributes.allowedFileTypes': 'Allowed file types',
        'attributes.maxFileSize': 'Maximum file size (in MB)',
        'attributes.options': 'Selection options',
        'attributes.conditions': 'Display conditions',
        'attributes.useOnly': 'Field is not saved',
        'attributes.codename': 'Codename',
        'attributes.isLarge': 'Large title',
        'attributes.onFullWidth': 'Full width',
        'attributes.products': 'Products',
        'attributes.fields': 'Fields included in calculation',
        'attributes.conditionsEval': 'Condition evaluation',
        'select.placeholder': 'Select an option',
        'select.field': 'Select field',
        'select.operator': 'Operator',
        'operator.equals': 'equals',
        'operator.not-equals': 'does not equal',
        'operator.contains': 'contains',
        'operator.not-contains': 'does not contain',
        'operator.empty': 'is empty',
        'operator.not-empty': 'is not empty',
        'operator.has-checked': 'is checked',
        images: 'Images',
        audios: 'Audio',
        videos: 'Videos',
        files: 'Files',
        add: 'Add',
        'option.title': 'Option title',
        checked: 'Checked',
        unchecked: 'Unchecked',
        'deleted.field': 'Deleted field',
        'no.fields': 'The form contains no fields',
        yes: 'Yes',
        no: 'No',
        'product.name': 'Product name',
        'product.price': 'Product price',
        and: 'All',
        or: 'At least one',
        'button.text': 'Button label',
    },
    sk: {
        'side.banner.title': 'Konfigurácia formulára',
        'side.banner.button': 'Konfigurovať',
        back: 'Späť',
        save: 'Uložiť',
        'success.message': 'Formulár bol úspešne uložený',
        'error.message': 'Nepodarilo sa uložiť formulár',
        'field.add': 'Pridať pole',
        'field.item.textinput': 'Textové pole',
        'field.item.email': 'Email',
        'field.item.phone': 'Telefónne číslo',
        'field.item.textarea': 'Viacriadkové pole',
        'field.item.checkbox': 'Zaškrtávacie políčko',
        'field.item.file': 'Súbor',
        'field.item.select': 'Výberová možnosť',
        'field.item.submit': 'Tlačidlo odoslať',
        'field.item.title': 'Nadpis',
        'field.item.message': 'Textová správa',
        'field.item.divider': 'Oddeľovač',
        'field.item.special': 'Špeciálne pole',
        'field.item.checkboxGroup': 'Skupina zaškrtávacích políčok',
        'field.item.productsSelection': 'Výber produktu',
        'field.item.amount': 'Celková cena',
        'unsaved.changes.title': 'Neuložené zmeny',
        'unsaved.changes.message': 'Ak opustíte túto stránku, stratíte neuložené zmeny.',
        'unsaved.changes.discard': 'Späť do editora',
        'unsaved.changes.confirm': 'Odísť bez uloženia',
        'attributes.name': 'Kľúč poľa',
        'attributes.name.hint': 'Kľúč sa generuje automaticky z názvu poľa, ale môžete ho zmeniť',
        'attributes.label': 'Názov poľa',
        'attributes.placeholder': 'Pomocný text (placeholder)',
        'attributes.required': 'Povinné pole',
        'attributes.maxFileCount': 'Maximálny počet súborov',
        'attributes.allowedFileTypes': 'Povolené typy súborov',
        'attributes.maxFileSize': 'Maximálna veľkosť súboru (v MB)',
        'attributes.options': 'Možnosti výberu',
        'attributes.conditions': 'Podmienky zobrazenia',
        'attributes.useOnly': 'Pole sa neukladá',
        'attributes.codename': 'Kódový názov',
        'attributes.isLarge': 'Veľký nadpis',
        'attributes.onFullWidth': 'Na celú šírku',
        'attributes.products': 'Produkty',
        'attributes.fields': 'Polia zahrnuté do výpočtu',
        'attributes.conditionsEval': 'Vyhodnocovanie podmienok',
        'select.placeholder': 'Vyberte možnosť',
        'select.field': 'Vybrať pole',
        'select.operator': 'Operátor',
        'operator.equals': 'rovná sa',
        'operator.not-equals': 'nerovná sa',
        'operator.contains': 'obsahuje',
        'operator.not-contains': 'neobsahuje',
        'operator.empty': 'je prázdne',
        'operator.not-empty': 'nie je prázdne',
        'operator.has-checked': 'je zaškrtnuté',
        images: 'Obrázky',
        audios: 'Zvuky',
        videos: 'Videá',
        files: 'Súbory',
        add: 'Pridať',
        'option.title': 'Názov možnosti',
        checked: 'Zaškrtnuté',
        unchecked: 'Nezaškrtnuté',
        'deleted.field': 'Vymazané pole',
        'no.fields': 'Formulár neobsahuje žiadne polia',
        yes: 'Áno',
        no: 'Nie',
        'product.name': 'Názov produktu',
        'product.price': 'Cena produktu',
        and: 'Všetky',
        or: 'Aspoň jeden',
        'button.text': 'Popis tlačidla',
    },
    de: {
        'side.banner.title': 'Formularkonfiguration',
        'side.banner.button': 'Konfigurieren',
        back: 'Zurück',
        save: 'Speichern',
        'success.message': 'Das Formular wurde erfolgreich gespeichert',
        'error.message': 'Das Formular konnte nicht gespeichert werden',
        'field.add': 'Feld hinzufügen',
        'field.item.textinput': 'Textfeld',
        'field.item.email': 'E-Mail',
        'field.item.phone': 'Telefonnummer',
        'field.item.textarea': 'Mehrzeiliges Feld',
        'field.item.checkbox': 'Kontrollkästchen',
        'field.item.file': 'Datei',
        'field.item.select': 'Auswahloption',
        'field.item.submit': 'Absenden-Button',
        'field.item.title': 'Titel',
        'field.item.message': 'Textnachricht',
        'field.item.divider': 'Trennlinie',
        'field.item.special': 'Spezialfeld',
        'field.item.checkboxGroup': 'Gruppe von Kontrollkästchen',
        'field.item.productsSelection': 'Produktauswahl',
        'field.item.amount': 'Gesamtpreis',
        'unsaved.changes.title': 'Nicht gespeicherte Änderungen',
        'unsaved.changes.message': 'Wenn Sie diese Seite verlassen, gehen nicht gespeicherte Änderungen verloren.',
        'unsaved.changes.discard': 'Zurück zum Editor',
        'unsaved.changes.confirm': 'Ohne Speichern verlassen',
        'attributes.name': 'Feldschlüssel',
        'attributes.name.hint': 'Der Schlüssel wird automatisch aus dem Feldnamen generiert, kann aber geändert werden',
        'attributes.label': 'Feldname',
        'attributes.placeholder': 'Platzhaltertext',
        'attributes.required': 'Pflichtfeld',
        'attributes.maxFileCount': 'Maximale Anzahl an Dateien',
        'attributes.allowedFileTypes': 'Erlaubte Dateitypen',
        'attributes.maxFileSize': 'Maximale Dateigröße (in MB)',
        'attributes.options': 'Auswahloptionen',
        'attributes.conditions': 'Anzeigebedingungen',
        'attributes.useOnly': 'Feld wird nicht gespeichert',
        'attributes.codename': 'Codename',
        'attributes.isLarge': 'Großer Titel',
        'attributes.onFullWidth': 'Volle Breite',
        'attributes.products': 'Produkte',
        'attributes.fields': 'Felder in Berechnung einbezogen',
        'attributes.conditionsEval': 'Bedingungsprüfung',
        'select.placeholder': 'Option auswählen',
        'select.field': 'Feld auswählen',
        'select.operator': 'Operator',
        'operator.equals': 'ist gleich',
        'operator.not-equals': 'ist nicht gleich',
        'operator.contains': 'enthält',
        'operator.not-contains': 'enthält nicht',
        'operator.empty': 'ist leer',
        'operator.not-empty': 'ist nicht leer',
        'operator.has-checked': 'ist ausgewählt',
        images: 'Bilder',
        audios: 'Audio',
        videos: 'Videos',
        files: 'Dateien',
        add: 'Hinzufügen',
        'option.title': 'Optionsbezeichnung',
        checked: 'Ausgewählt',
        unchecked: 'Nicht ausgewählt',
        'deleted.field': 'Gelöschtes Feld',
        'no.fields': 'Das Formular enthält keine Felder',
        yes: 'Ja',
        no: 'Nein',
        'product.name': 'Produktname',
        'product.price': 'Produktpreis',
        and: 'Alle',
        or: 'Mindestens eines',
        'button.text': 'Button-Beschriftung',
    },
    fr: {
        'side.banner.title': 'Configuration du formulaire',
        'side.banner.button': 'Configurer',
        back: 'Retour',
        save: 'Enregistrer',
        'success.message': 'Le formulaire a été enregistré avec succès',
        'error.message': "Échec de l'enregistrement du formulaire",
        'field.add': 'Ajouter un champ',
        'field.item.textinput': 'Champ de texte',
        'field.item.email': 'E-mail',
        'field.item.phone': 'Numéro de téléphone',
        'field.item.textarea': 'Champ multiligne',
        'field.item.checkbox': 'Case à cocher',
        'field.item.file': 'Fichier',
        'field.item.select': 'Option de sélection',
        'field.item.submit': "Bouton d'envoi",
        'field.item.title': 'Titre',
        'field.item.message': 'Message texte',
        'field.item.divider': 'Séparateur',
        'field.item.special': 'Champ spécial',
        'field.item.checkboxGroup': 'Groupe de cases à cocher',
        'field.item.productsSelection': 'Sélection de produits',
        'field.item.amount': 'Prix total',
        'unsaved.changes.title': 'Modifications non enregistrées',
        'unsaved.changes.message': 'Si vous quittez cette page, vous perdrez les modifications non enregistrées.',
        'unsaved.changes.discard': 'Retour à l’éditeur',
        'unsaved.changes.confirm': 'Quitter sans enregistrer',
        'attributes.name': 'Clé du champ',
        'attributes.name.hint':
            'La clé est générée automatiquement à partir du nom du champ, mais vous pouvez la modifier',
        'attributes.label': 'Nom du champ',
        'attributes.placeholder': 'Texte indicatif (placeholder)',
        'attributes.required': 'Champ obligatoire',
        'attributes.maxFileCount': 'Nombre maximal de fichiers',
        'attributes.allowedFileTypes': 'Types de fichiers autorisés',
        'attributes.maxFileSize': 'Taille maximale du fichier (en Mo)',
        'attributes.options': 'Options de sélection',
        'attributes.conditions': 'Conditions d’affichage',
        'attributes.useOnly': 'Champ non enregistré',
        'attributes.codename': 'Nom de code',
        'attributes.isLarge': 'Grand titre',
        'attributes.onFullWidth': 'Pleine largeur',
        'attributes.products': 'Produits',
        'attributes.fields': 'Champs inclus dans le calcul',
        'attributes.conditionsEval': 'Évaluation des conditions',
        'select.placeholder': 'Sélectionnez une option',
        'select.field': 'Sélectionner un champ',
        'select.operator': 'Opérateur',
        'operator.equals': 'égal à',
        'operator.not-equals': 'n’est pas égal à',
        'operator.contains': 'contient',
        'operator.not-contains': 'ne contient pas',
        'operator.empty': 'est vide',
        'operator.not-empty': 'n’est pas vide',
        'operator.has-checked': 'est coché',
        images: 'Images',
        audios: 'Audios',
        videos: 'Vidéos',
        files: 'Fichiers',
        add: 'Ajouter',
        'option.title': 'Titre de l’option',
        checked: 'Coché',
        unchecked: 'Non coché',
        'deleted.field': 'Champ supprimé',
        'no.fields': 'Le formulaire ne contient aucun champ',
        yes: 'Oui',
        no: 'Non',
        'product.name': 'Nom du produit',
        'product.price': 'Prix du produit',
        and: 'Tous',
        or: 'Au moins un',
        'button.text': 'Libellé du bouton',
    },
    es: {
        'side.banner.title': 'Configuración del formulario',
        'side.banner.button': 'Configurar',
        back: 'Volver',
        save: 'Guardar',
        'success.message': 'El formulario se guardó correctamente',
        'error.message': 'No se pudo guardar el formulario',
        'field.add': 'Agregar campo',
        'field.item.textinput': 'Campo de texto',
        'field.item.email': 'Correo electrónico',
        'field.item.phone': 'Número de teléfono',
        'field.item.textarea': 'Campo multilínea',
        'field.item.checkbox': 'Casilla de verificación',
        'field.item.file': 'Archivo',
        'field.item.select': 'Opción de selección',
        'field.item.submit': 'Botón de envío',
        'field.item.title': 'Título',
        'field.item.message': 'Mensaje de texto',
        'field.item.divider': 'Separador',
        'field.item.special': 'Campo especial',
        'field.item.checkboxGroup': 'Grupo de casillas',
        'field.item.productsSelection': 'Selección de productos',
        'field.item.amount': 'Precio total',
        'unsaved.changes.title': 'Cambios no guardados',
        'unsaved.changes.message': 'Si abandonas esta página, perderás los cambios no guardados.',
        'unsaved.changes.discard': 'Volver al editor',
        'unsaved.changes.confirm': 'Salir sin guardar',
        'attributes.name': 'Clave del campo',
        'attributes.name.hint':
            'La clave se genera automáticamente a partir del nombre del campo, pero puedes cambiarla',
        'attributes.label': 'Nombre del campo',
        'attributes.placeholder': 'Texto de ayuda (placeholder)',
        'attributes.required': 'Campo obligatorio',
        'attributes.maxFileCount': 'Cantidad máxima de archivos',
        'attributes.allowedFileTypes': 'Tipos de archivo permitidos',
        'attributes.maxFileSize': 'Tamaño máximo del archivo (en MB)',
        'attributes.options': 'Opciones de selección',
        'attributes.conditions': 'Condiciones de visualización',
        'attributes.useOnly': 'El campo no se guarda',
        'attributes.codename': 'Nombre en código',
        'attributes.isLarge': 'Título grande',
        'attributes.onFullWidth': 'Ancho completo',
        'attributes.products': 'Productos',
        'attributes.fields': 'Campos incluidos en el cálculo',
        'attributes.conditionsEval': 'Evaluación de condiciones',
        'select.placeholder': 'Selecciona una opción',
        'select.field': 'Seleccionar campo',
        'select.operator': 'Operador',
        'operator.equals': 'es igual a',
        'operator.not-equals': 'no es igual a',
        'operator.contains': 'contiene',
        'operator.not-contains': 'no contiene',
        'operator.empty': 'está vacío',
        'operator.not-empty': 'no está vacío',
        'operator.has-checked': 'está marcado',
        images: 'Imágenes',
        audios: 'Audios',
        videos: 'Videos',
        files: 'Archivos',
        add: 'Agregar',
        'option.title': 'Título de la opción',
        checked: 'Marcado',
        unchecked: 'No marcado',
        'deleted.field': 'Campo eliminado',
        'no.fields': 'El formulario no contiene campos',
        yes: 'Sí',
        no: 'No',
        'product.name': 'Nombre del producto',
        'product.price': 'Precio del producto',
        and: 'Todos',
        or: 'Al menos uno',
        'button.text': 'Etiqueta del botón',
    },
};

export const getSystemResource = (key: string, locale: 'cs' | 'en') => {
    const empty = `{${key}}`;

    return DATA[locale][key] || empty;
};
