const DATA: Record<string, any> = {
    cs: {
        'side.banner.title': 'Konfigurace formuláře',
        'side.banner.button': 'Konfigurovat',
        back: 'Zpět',
        save: 'Uložit',
        'success.message': 'Formulář byl úspěšně uložen',
        'error.message': 'Formulář se nepodařilo uložit',
        'field.add': 'Přidat pole',
        'field.item.textinput': 'Textové pole',
        'field.item.email': 'E-mail',
        'field.item.phone': 'Mobilní číslo',
        'field.item.textarea': 'Víceřádkové pole',
        'field.item.checkbox': 'Zaškrtávací políčko',
        'field.item.file': 'Soubor',
        'field.item.select': 'Výběr možnosti',
        'field.item.submit': 'Tlačítko odeslat',
        'field.item.title': 'Nadpis',
        'field.item.message': 'Textová zpráva',
        'field.item.divider': 'Dělicí čára',
        'field.item.special': 'Speciální pole',
        'field.item.checkboxGroup': 'Skupina zaškrtávacích políček',
        'field.item.productsSelection': 'Výběr produktů',
        'field.item.amount': 'Součet ceny',
        'unsaved.changes.title': 'Neuložené změny',
        'unsaved.changes.message': 'Pokud opustíte tuto stránku, ztratíte neuložené změny.',
        'unsaved.changes.discard': 'Zpět do editoru',
        'unsaved.changes.confirm': 'Odejít bez uložení',
        'attributes.name': 'Klíč pole',
        'attributes.name.hint': 'Klíč je automaticky generován z názvu pole, ale můžete ho změnit',
        'attributes.label': 'Název pole',
        'attributes.placeholder': 'Zástupný text',
        'attributes.required': 'Povinné pole',
        'attributes.maxFileCount': 'Maximální počet souborů',
        'attributes.allowedFileTypes': 'Povolené typy souborů',
        'attributes.maxFileSize': 'Maximální velikost souboru (v MB)',
        'attributes.options': 'Možnosti výběru',
        'attributes.conditions': 'Podmínky zobrazení',
        'attributes.useOnly': 'Pole se neukládá',
        'attributes.codename': 'Kódové označení',
        'attributes.isLarge': 'Velký nadpis',
        'attributes.onFullWidth': 'Na celou šířku',
        'attributes.products': 'Produkty',
        'attributes.fields': 'Pole zahrnutá do výpočtu',
        'attributes.conditionsEval': 'Vyhodnocení podmínek',
        'select.placeholder': 'Vyberte možnost',
        'select.field': 'Vyberte pole',
        'select.operator': 'Operátor',
        'operator.equals': 'je rovno',
        'operator.not-equals': 'není rovno',
        'operator.contains': 'obsahuje',
        'operator.not-contains': 'neobsahuje',
        'operator.empty': 'je prázdné',
        'operator.not-empty': 'není prázdné',
        'operator.has-checked': 'má zaškrtnuto',
        images: 'Obrázky',
        audios: 'Zvuky',
        videos: 'Videa',
        files: 'Soubory',
        add: 'Přidat',
        'option.title': 'Název možnosti',
        checked: 'Zaškrtnuto',
        unchecked: 'Není zaškrtnuto',
        'deleted.field': 'Smazané pole',
        'no.fields': 'Formulář neobsahuje žádná pole',
        yes: 'Ano',
        no: 'Ne',
        'product.name': 'Název produktu',
        'product.price': 'Cena produktu',
        and: 'Všechny',
        or: 'Alespoň jedna',
    },
    en: {
        'side.banner.title': 'Form Configuration',
        'side.banner.button': 'Configure',
        back: 'Back',
        save: 'Save',
        'success.message': 'The form was successfully saved',
        'error.message': 'Failed to save the form',
        'field.add': 'Add field',
        'field.item.textinput': 'Text field',
        'field.item.email': 'Email',
        'field.item.phone': 'Mobile number',
        'field.item.textarea': 'Multiline field',
        'field.item.checkbox': 'Checkbox',
        'field.item.file': 'File',
        'field.item.select': 'Select option',
        'field.item.submit': 'Submit button',
        'field.item.title': 'Title',
        'field.item.message': 'Text message',
        'field.item.divider': 'Divider',
        'field.item.special': 'Special field',
        'field.item.checkboxGroup': 'Checkbox group',
        'field.item.productsSelection': 'Product selection',
        'field.item.amount': 'Total price',
        'unsaved.changes.title': 'Unsaved changes',
        'unsaved.changes.message': 'If you leave this page, you will lose unsaved changes.',
        'unsaved.changes.discard': 'Back to editor',
        'unsaved.changes.confirm': 'Leave without saving',
        'attributes.name': 'Field key',
        'attributes.name.hint': 'The key is automatically generated from the field name, but you can change it',
        'attributes.label': 'Field name',
        'attributes.placeholder': 'Placeholder text',
        'attributes.required': 'Required field',
        'attributes.maxFileCount': 'Maximum number of files',
        'attributes.allowedFileTypes': 'Allowed file types',
        'attributes.maxFileSize': 'Maximum file size (in MB)',
        'attributes.options': 'Selection options',
        'attributes.conditions': 'Display conditions',
        'attributes.useOnly': 'Field is not saved',
        'attributes.codename': 'Codename',
        'attributes.isLarge': 'Large title',
        'attributes.onFullWidth': 'Full width',
        'attributes.products': 'Products',
        'attributes.fields': 'Fields included in calculation',
        'attributes.conditionsEval': 'Condition evaluation',
        'select.placeholder': 'Select an option',
        'select.field': 'Select field',
        'select.operator': 'Operator',
        'operator.equals': 'equals',
        'operator.not-equals': 'does not equal',
        'operator.contains': 'contains',
        'operator.not-contains': 'does not contain',
        'operator.empty': 'is empty',
        'operator.not-empty': 'is not empty',
        'operator.has-checked': 'is checked',
        images: 'Images',
        audios: 'Audio',
        videos: 'Videos',
        files: 'Files',
        add: 'Add',
        'option.title': 'Option title',
        checked: 'Checked',
        unchecked: 'Unchecked',
        'deleted.field': 'Deleted field',
        'no.fields': 'The form contains no fields',
        yes: 'Yes',
        no: 'No',
        'product.name': 'Product name',
        'product.price': 'Product price',
        and: 'All',
        or: 'At least one',
    },
};

export const getSystemResource = (key: string, locale: 'cs' | 'en') => {
    const empty = `{${key}}`;

    return DATA[locale][key] || empty;
};
